# Menu
menu:
  主页: /
  归档: /archives
#  Gallery: /gallery
  关于: /about
#rss: /atom.xml

# Miscellaneous
favicon: /favicon.ico
brand: /images/hexo.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  brand: /images/hexo-inverted.svg

# Content
excerpt_link: 阅读更多..

# Tags
show_count: false

# Toc
toc: true

# fancybox
fancybox: true

# Local search
search_text: Search

# Gitalk
gitalk:
  enable: false # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

# Valine
valine:
  enable: true # true
  el: 'vcomments'
  appId: zX1WYifJaMoEaMytlMiSORoM-9Nh9j0Va
  appKey: 16MkNPNchKqt1YK1YRtILpva
  notify: true
  verify: true
  avatar: 'mp'
  pageSize: '10'
  language: zh-cn
  comment_count: true
  placeholder: '请输入...'

# cdn config
vendors:
  # valine
  # See: https://github.com/xCss/Valine
  # Example:
  # valine: //cdn.jsdelivr.net/npm/valine@1/dist/Valine.min.js
  # valine: //cdnjs.cloudflare.com/ajax/libs/valine/1.3.4/Valine.min.js
  valine: //cdn.jsdelivr.net/npm/valine@1/dist/Valine.min.js

